select * from Sport
select * from SportType
select * from SportSubType
select * from SchoolsSportsSubtypes
select * from School
select * from Participant
select * from ParticipantsCompetitions
select * from Competition
select * from EventsCompetitions
select * from [Event]
select * from [Image]
select * from ImagesUsers
select * from Contact
select * from [User]
select * from [Role]